create or replace pipe CUSTOMER_DATA_PIPE auto_ingest=true as COPY INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, IS_ACTIVE)
    FROM @INTERNAL_DATA_STAGE
    FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1)
    ON_ERROR = 'CONTINUE';
