create or replace TABLE CUSTOMERS (
	CUSTOMER_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100),
	CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	unique (EMAIL)
);
