create or replace TABLE ORDER_ITEMS cluster by (ORDER_ID, CREATED_AT)(
	ITEM_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	ORDER_ID NUMBER(38,0) NOT NULL,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	QUANTITY NUMBER(38,0) NOT NULL,
	UNIT_PRICE NUMBER(10,2) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
