create or replace TABLE ORDERS (
	ORDER_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	ORDER_DATE DATE NOT NULL,
	TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
	STATUS VARCHAR(20) DEFAULT 'PENDING'
);
