create or replace view ACTIVE_CUSTOMERS(
	CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	CREATED_DATE
) as
SELECT 
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CREATED_DATE
FROM CUSTOMERS 
WHERE IS_ACTIVE = TRUE;
