create or replace view CUSTOMER_ORDER_SUMMARY(
	CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME,
	TOTAL_ORDERS,
	TOTAL_SPENT,
	LAST_ORDER_DATE
) as
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    COUNT(o.ORDER_ID) as TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_SPENT,
    MAX(o.ORDER_DATE) as LAST_ORDER_DATE
FROM CUSTOMERS c
LEFT JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE c.IS_ACTIVE = TRUE
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME;
