create or replace materialized view DAILY_SALES_SUMMARY(
	SALE_DATE,
	TOTAL_ORDERS,
	DAILY_REVENUE,
	AVG_ORDER_VALUE
) as
SELECT 
    DATE(ORDER_DATE) as SALE_DATE,
    COUNT(*) as TOTAL_ORDERS,
    SUM(TOTAL_AMOUNT) as DAILY_REVENUE,
    AVG(TOTAL_AMOUNT) as AVG_ORDER_VALUE
FROM ORDERS
WHERE STATUS != 'CANCELLED'
GROUP BY DATE(ORDER_DATE);
